### ISSUE TITLE
repository /assets .. not found

### ISSUE THREAD

**Issue by mes1moha** [CoderDojoChi/survy#60]
Hi,
i had this error when i wanted to try this project
![survyerror](https://user-images.githubusercontent.com/45790352/49976519-a53d9100-ff42-11e8-8eb0-aca781fcf3ab.PNG)
Help please !!

**Comment by karbassi** [comment]
@mes1moha great question.

This is an old project (2014) and a lot of the code probably won't work anymore. However, the error you're seeing it because `gulp` wasn't ran. 

I looked at this code and seems like updating will take a while.

**Comment by mes1moha** [comment]
@karbassi  thank you ;)
